Repository lalitj/taskcrm, pull requests merged in 2021-04, with the labels that each got.

#1 Client CRUD
  app/Http/Controllers/ClientsController.php
  app/Http/Controllers/TasksController.php
  app/Models/Account.php
  app/Models/Client.php
  app/Models/Task.php
  database/factories/ClientFactory.php
  database/factories/TaskFactory.php
  database/migrations/2020_01_01_000005_create_clients_table.php
  database/migrations/2020_01_01_000005_create_tasks_table.php
  database/seeds/DatabaseSeeder.php
  resources/js/Pages/Clients/Create.vue
  resources/js/Pages/Clients/Edit.vue
  resources/js/Pages/Clients/Index.vue
  resources/js/Pages/Tasks/Create.vue
  resources/js/Pages/Tasks/Edit.vue
  resources/js/Pages/Tasks/Index.vue
  resources/js/Shared/MainMenu.vue
  routes/web.php
Labels: waiting-pr

#2 Task CRUD
  app/Http/Controllers/TasksController.php
  app/Models/Account.php
  app/Models/Task.php
  database/factories/TaskFactory.php
  database/migrations/2020_01_01_000005_create_tasks_table.php
  database/seeds/DatabaseSeeder.php
  resources/js/Pages/Tasks/Create.vue
  resources/js/Pages/Tasks/Edit.vue
  resources/js/Pages/Tasks/Index.vue
  resources/js/Shared/MainMenu.vue
  routes/web.php
Labels: in-progress

#3 Task CRUD
  app/Http/Controllers/TasksController.php
  app/Models/Account.php
  app/Models/Task.php
  database/factories/TaskFactory.php
  database/migrations/2020_01_01_000005_create_tasks_table.php
  database/seeds/DatabaseSeeder.php
  resources/js/Pages/Tasks/Create.vue
  resources/js/Pages/Tasks/Edit.vue
  resources/js/Pages/Tasks/Index.vue
  resources/js/Shared/MainMenu.vue
  routes/web.php
Labels: in-progress

#4 Address CRUD
  app/Http/Controllers/AddressesController.php
  app/Http/Controllers/BanksController.php
  app/Models/Account.php
  app/Models/Address.php
  app/Models/Bank.php
  database/factories/AddressFactory.php
  database/factories/BankFactory.php
  database/migrations/2020_01_01_000005_create_addresses_table.php
  database/migrations/2020_01_01_000005_create_banks_table.php
  database/seeds/DatabaseSeeder.php
  resources/js/Pages/Addresses/Create.vue
  resources/js/Pages/Addresses/Edit.vue
  resources/js/Pages/Addresses/Index.vue
  resources/js/Pages/Banks/Create.vue
  resources/js/Pages/Banks/Edit.vue
  resources/js/Pages/Banks/Index.vue
  resources/js/Shared/MainMenu.vue
  routes/web.php
Labels: in-progress

#7 Mk/crud experiences
  app/Http/Controllers/AddressesController.php
  app/Http/Controllers/BudgetsController.php
  app/Http/Controllers/CommentsController.php
  app/Http/Controllers/DocumentsController.php
  app/Http/Controllers/ExperiencesController.php
  app/Http/Controllers/ProfilesController.php
  app/Http/Controllers/RestaurantsController.php
  app/Models/Account.php
  app/Models/Budget.php
  app/Models/Comment.php
  app/Models/Document.php
  app/Models/Experience.php
  app/Models/Profile.php
  database/factories/BudgetFactory.php
  database/factories/CommentFactory.php
  database/factories/DocumentFactory .php
  database/factories/ExperienceFactory.php
  database/factories/ProfileFactory.php
  database/factories/RestaurantFactory.php
  database/migrations/2020_01_01_000005_create_budgets_table.php
  database/migrations/2020_01_01_000005_create_comments_table.php
  database/migrations/2020_01_01_000005_create_documents_table.php
  database/migrations/2020_01_01_000005_create_experiences_table.php
  database/migrations/2020_01_01_000005_create_profiles_table.php
  database/migrations/2020_01_01_000005_create_restaurants_table.php
  database/seeds/DatabaseSeeder.php
  resources/js/Pages/Auth/Login.vue
  resources/js/Pages/Budgets/Create.vue
  resources/js/Pages/Budgets/Edit.vue
  resources/js/Pages/Budgets/Index.vue
  resources/js/Pages/Comments/Create.vue
  resources/js/Pages/Comments/Edit.vue
  resources/js/Pages/Comments/Index.vue
  resources/js/Pages/Documents/Create.vue
  resources/js/Pages/Documents/Edit.vue
  resources/js/Pages/Documents/Index.vue
  resources/js/Pages/Experiences/Create.vue
  resources/js/Pages/Experiences/Edit.vue
  resources/js/Pages/Experiences/Index.vue
  resources/js/Pages/Profiles/Create.vue
  resources/js/Pages/Profiles/Edit.vue
  resources/js/Pages/Profiles/Index.vue
  resources/js/Pages/Restaurants/Create.vue
  resources/js/Pages/Restaurants/Edit.vue
  resources/js/Pages/Restaurants/Index.vue
  resources/js/Shared/MainMenu.vue
  routes/web.php
  tests/Feature/ExperiencesTest.php
Labels: ready-to-merge
